apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_DRIVER: "mysql"
  DB_PARSETIME: "true"
  DB_PORT: "3306"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD:

  APP_PORT: "9090"
